- src/connectors/valora/valoraUtils.ts
- src/index.tsx
- src/pages/App.tsx
When accessing Ubeswap on Chome on Android devices, Valora redirects back to a new Ubeswap tab after connecting, causing the original Ubeswap tab to hang. The fix is inspired by https://github.com/AlexBHarley/use-contractkit/blob/master/packages/use-contractkit/src/dappkit-wallet/dappkit.ts, which stores the redirect params in `localStorage` and closes out the new tab.
> Fix Valora opening separate tab

- src/pages/App.tsx
- src/utils/mobile.ts
- Only do window.close() on Android
- Assumes Android always causes a new window to pop up
- Add some mobile utils
- Call `useEffect` in App.tsx for any location change
> Fix Valora regression on iOS

- src/state/stake/hooks.ts
Bug: The app currently crashes when you open up UbeBalanceContent to look at your total UBE rewards.
It looks like now that there are rewards that aren't just in UBE, the current logic crashes, failing the invariant for adding token amounts. This adds a check to make sure that the reward token for each stake is UBE before adding it
> Fix Total Ube Calculation

- src/components/earn/PoolCard.tsx
Noticed that the APY formula is wrong - should be: `APY=(1 + APR/n)^n – 1`
With the current formula, even a minimal APR (e.g. 0.1%) would lead to a APY > 100%
> Fix APY formula

- public/locales/en.json
- src/pages/Earn/index.tsx
- src/state/stake/useOwnerStakedPools.ts
To make it easier to manage your farmed pools, this PR moves "Your Pools" to the top, sorted by "Triple Reward Pools", "Double Reward Pools", "Your Pools", and then "Your Inactive Pools"
This is done by doing the following:
1. Creating a new hook useOwnerStakedPools
2. Fetching all the balances of all the multirewardpools and checking which ones are greater than zero, so we know what is staked
3. Displaying it properly in the UI
See screencast here: https://watch.screencastify.com/v/4NyR5f6M4E0QSgQYMUB4
> Move "Your Pools" to the top of Farm Page

- src/pages/Send/index.tsx
Pressing "max" on the send page would show an insufficient funds message. 
change `!lessThan` to `greaterThan` so that `==` case does not trigger the nsf. 
https://user-images.githubusercontent.com/3814795/140854983-3dafeece-cb20-4345-b3f2-6b02f81d9ea7.mov
> fix pressing max should be sendable, remove false nsf error

- src/pages/App.tsx
- src/pages/Earn/index.tsx
- src/state/multicall/updater.tsx
* reduce empty space at top of page
* change multicall canceler to only cancel if blocks are 2 blocks behind. This should help with loading since before any fetch that took more than 5 seconds was discarded.
> Farm page minor Improvements

- src/index.tsx
fixing 
Error: src/index.tsx(114,6): error TS2741: Property 'network' is missing in type '{ children: Element; dapp: { name: string; description: string; url: string; icon: string; }; networks: ({ readonly name: NetworkNames.CeloMainnet; readonly rpcUrl: "https://forno.celo.org"; readonly graphQl: "https://explorer.celo.org/graphiql"; readonly explorer: "https://explorer.celo.org"; readonly chainId: Chai...' but required in type 'ContractKitProviderProps'
> add network to fix type issue

- src/pages/Earn/index.tsx
- src/state/stake/useOwnerStakedPools.ts
When there are two farms for a pool this dedups so that only the best one is shown. 
Note this only dedups *unstaked* farms, my thinking there is that I dont want people worrying about where their farms went. 
Uploading Screen Recording 2021-11-13 at 12.45.56 PM.mov…
> Dedupes unstaked farms, showing only the one with the most rewards.

- src/components/Header/index.tsx
- src/components/WalletModal/Option.tsx
Fixes Ubeswap Logo overflow with the nav on smaller devices by removing it and for very small devices reducing space between nav items
fixes a light house complaint about img missing height and width. this helps with reducing reflowing on render
> Fixes mobile nav overflow + relayout 

- src/components/earn/PoolCard.tsx
on mobile the wrong value was showing and APY was erroneously displayed no matter what the preference was. now follows same behavior as desktop. 
https://user-images.githubusercontent.com/3814795/142701513-b77389ab-fe74-407f-8c84-048b066ca13a.mov
Also add aria label to explain that pressing toggles for screen readers
> Fix APR on mobile and allow users to toggle. 

- src/pages/Earn/Manage.tsx
- src/pages/Earn/useStakingPoolValue.tsx
pass the stakingTokenPair directly into useStakingPoolValue, otherwise it waits until the staking info is available to get the token prices but since we already have the tokens we can parallel the work
> Farm Manage Page Data Efficiency

- src/components/earn/PoolCard.tsx
1 adds a (minus 1) to the formula so that we end up with rates like (45% not 145%) 
2 changes variable name for the simple apr to` apr `not `apy` cause that was confusing!
3 moves the calculation into its own function for better readability
> Fix Yield calculation

- src/data/Reserves.ts
- src/pages/Pool/index.tsx
- src/utils/useCUSDPrice.ts
Several Places were were passing array reference that would change every render to a userMemo deps array. This fixes that including a few places where there was a  `.map` outside of a memo which could have been inside it
> Memo Fixes

- src/components/earn/PoolCard.tsx
- src/pages/Earn/Manage.tsx
- src/state/stake/useDualStakeRewards.ts
1. Sometimes rewards end when this happens it would say 0 TOKENS / Week. now this skips except for the earned/unclaimed if the zero rewards tokens still has unclaimed rewards. 
2. If earned amount is less than 0.0001 tokens display more digits rather than rounding down to zero 
3. when displaying staked amounts show sigificant digits when amount is less than one, and 1 decimals when 1 < x < 10.
> Tighten Up reward and staking displays

- src/pages/AddLiquidity/PoolPriceBar.tsx
Fix: When 0 is used in liquidity page, there was unexpected error that says "Division by 0"
> fix: Division by 0 error when 0 is used on the add liquidity page

- public/locales/en.json
Fixed spell of "Featrued Pools" to "Featured Pools"
> fix: Featured Pools spelling issue

- src/components/Stake/StakeInputField.tsx
- src/pages/Stake/index.tsx
fix: UI issues on stake page
- Your Weekly Rewards pod:
Background consistency: Match background color with Your Ube Stake pod, so either both beige or both gray. 
Capitalization consistency: Change "Your weekly rewards" to "Your Weekly Rewards" and "Annual stake APR" to "Annual Stake APR"
Alignment consistency: Right justify the amount of Unclaimed Rewards by moving purple Claim button either before it, or directly underneath it 
- Community UBE Stake pod:
Sizing consistency: reduce size of View UBE Contract and View UBE Chart to match Total UBE Staked and Your UBE Stake Pool Share
- Your UBE stake pod
Change title from "Your UBE stake" to "Your UBE Stake"
When viewed in vertical mobile view, the amount underneath Current Stake and Wallet Balance moves to the line below which throws off …
> fix: ui issues on stake page

- src/state/stake/useOwnerStakedPools.ts
We have several farms for single lp token and that's why we could see the different APRs for same pools.
So I have removed duplicated farms in the farm page and left best farms(The farm that has the highest rewards)
> fix: apr mismatches in farm page

- src/constants/index.ts
- src/hooks/romulus/useProposals.ts
- src/hooks/romulus/useVoteCasts.ts
- src/hooks/useContract.ts
- src/pages/Earn/useFarmRegistry.ts
- src/pages/LimitOrder/executCancelOrder.tsx
- src/pages/LimitOrder/useOrderBroadcasted.tsx
- src/utils/fetchEvents.ts
Celo public RPCs has problem when fetching all events. So I have added an infura url as an alternative rpc url. But the old forno url will be used too in case of infura failure.  Also web3.js codes on farm pages refactored to ethers.js too.
With this fix, loading problems on governance, farm, limit order and pool pages should be fixed.
> Alternative RPC for fetching events
