Ubeswap/ubeswap-interface

- src/components/AccountDetails/index.tsx
- src/components/WalletModal/LedgerWalletSelector/LedgerAddress.tsx
- src/components/WalletModal/LedgerWalletSelector/index.tsx
- src/components/WalletModal/index.tsx
- src/connectors/ledger/LedgerConnector.ts
Fixes https://github.com/Ubeswap/ubeswap-interface/issues/16
> Implement modal to select ledger wallets

- src/state/lists/ubeswap-default.tokenlist.json
> adding cMCO2

- package.json
- yarn.lock
This reverts commit fa167e6028f6fd3eb0c77bc934510eae90a1b8d6.
> Revert "Install Sentry CLI (#194)"

- src/components/PositionCard/index.tsx
- src/components/swap/routing/TradeDetails/UbeswapTradeDetails.tsx
- src/pages/Pool/index.tsx
Update the UI to show the correct swap fee allocations.
> Update fees on UI to account for 0.05% buy back

- src/pages/Earn/index.tsx
load pools when ready rather than requiring all to be ready.
This should marginally help. if some pools are slower to load than others
> load pools when ready rather than requiring all to be ready.

- src/pages/Earn/useFarmRegistry.ts
fixes 
`useFarmRegistry.ts:64 Uncaught (in promise) TypeError: …Cannot read properties of undefined (reading 'tvlUSD')`
> fix farm page 

- package.json
- yarn.lock
This dramatically reduces the number of requests to forno we were getting from hundreds (400-700) to less than 100
> upgrade use-contract kit, reduce calls to forno for chain id

- src/components/earn/PoolCard.tsx
Pools which are new were not showing. due to divide by zero error.
> fix pools with no tvl not showing on farm page

- src/components/CurrencyInputPanel/CurrencySelect.tsx
- src/components/CurrencyInputPanel/TokenSelect.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/earn/PoolCard.tsx
- src/pages/Earn/index.tsx
- src/pages/Earn/useFarmRegistry.ts
New feature for filtering farms as requested by community
https://user-images.githubusercontent.com/3814795/142552837-5e293fd8-d004-4fdb-90ba-e54bed9d557d.mov
- fixed farms aprs on non dark mode on mobile being unreadable 
- center and enlarge the spinner 
- promise all to speed up load times
> [FEAT] add farm filtering by token

- public/locales/en.json
- src/pages/Earn/index.tsx
- src/pages/Earn/useFarmRegistry.ts
- src/state/stake/useOwnerStakedPools.ts
Feat: Add featured pools section to farm page
> Add featured pools section to Farm page

- src/components/Header/OpticsV1Warning.tsx
- src/pages/Swap/index.tsx
Add Warning for optics v1 tokens, urging users to migrate or bridge the tokens.
https://watch.screencastify.com/v/VrBVnytlpj7hwWwSrd9D
> add warning for optics v1 tokens

- src/components/Stake/StakeInputField.tsx
- src/pages/Stake/index.tsx
feat: stake page redesign from wireframe
> feat: stake page redesign

- src/components/Header/BridgeMenuGroup.tsx
- src/components/Header/index.tsx
Added orbit to the bridge dropdown
> feat: add orbit to the bridge dropdown

- src/components/Header/BridgeMenuGroup.tsx
- src/components/Header/ChartsMenuGroup.tsx
- src/components/Header/NavMenu.tsx
Import `StyledNavMenu` for `ChartsMenuGroup` to reduce code duplication
> Charts Header Refactor

- src/constants/abis/moola/moola-staking-rewards.ts
- src/state/stake/farms.ts
- src/state/stake/hooks.ts
This reverts commit 88e252def18bde8338c8b82c808271a2e3e8d1d3.
> Revert "multiPoolRewards-refactor (#504)"

- src/pages/LimitOrder/index.tsx
replace `Total` label for how much the user will buy or sell, instead:
Total buy: 
Total cost:
or for Selling
Total sell:
Total received:
> Replace Total with more explicit descriptions of sell / buy action

- src/components/earn/ImportFarmModal.tsx
- src/components/earn/PoolCard.tsx
- src/hooks/Tokens.ts
- src/pages/Earn/ManageSingle.tsx
- src/pages/Earn/index.tsx
- src/pages/Earn/useCustomStakingInfo.ts
- src/pages/Earn/useFarmRegistry.ts
- src/pages/Earn/useLPValue.tsx
Fix issue on import farm for newly created tokens
> fix: issue for importing farm of newly created tokens

- package.json
- src/components/Header/index.tsx
- src/components/SearchModal/ChainSearchModal.tsx
- src/components/SearchModal/CurrencySearch.tsx
- src/constants/multicall/index.ts
- src/constants/poolManager.ts
- src/hooks/useIsSupportedNetwork.ts
- src/networks/index.ts
- src/state/application/actions.ts
- src/state/lists/hooks.ts
- src/state/stake/hooks.ts
- src/state/swap/hooks.ts
- src/state/user/actions.ts
- yarn.lock
- perf: upgrade @celo-tools/use-contractkit to latest version 3.1.0
Tested Scenarios with latest version:
Ledger (desktop + Chrome)
- tested connectivity
- tested swaps
Valora (iOS version 1.33.0)
- tested connectivity via QR code on desktop
- tested connectivity and swapping on iOS Safari + Valora App
- tested claiming rewards from farm on desktop
- test swapping on desktop
MetaMask (desktop + Chrome)
- tested connectivity
- tested swap
- tested placing Limit Order
Celo Terminal (desktop app + Chrome)
- tested connectivity
- tested swap
- tested claiming rewards from farm
WalletConnect (Celo Terminal + Chrome)
- tested connectivity via Celo Terminal
> WIP: Upgrade @celo-tools/use-contractkit to latest version 3.1.0

- src/components/Header/BridgeMenuGroup.tsx
- src/components/Header/index.tsx
Add transferto into Bridge list
> feat: add transferto into Bridge

- src/components/earn/StakingModal.tsx
- src/pages/Earn/Manage.tsx
- src/pages/Earn/useStakingPoolValue.tsx
- src/utils/useCUSDPrice.ts
Fix issue for importing ULP farm in farm page and farm details page
> fix: issue for importing ULP farm in farm and farm details page

- src/components/earn/PoolCard.tsx
- src/components/earn/StakedAmountsHelper.tsx
- src/pages/Earn/index.tsx
- src/pages/Earn/useLPValue.tsx
optimize speed in farm page by preventing redraw doms from unchanged props
> optimize speed in farm page
